# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('acronym', models.CharField(max_length=5)),
                ('locn', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mocktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('p3', models.IntegerField()),
                ('p4', models.IntegerField()),
                ('p5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('clg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrnd.college')),
                ('mtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrnd.mocktest')),
            ],
        ),
    ]
