# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0002_remove_mocktest_p5'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='dbfolder',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
