# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0003_college_dbfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='locn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
