# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0004_auto_20160601_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='dbfolder',
        ),
        migrations.AddField(
            model_name='student',
            name='dbfolder',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
