# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0005_auto_20160601_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem1', models.IntegerField()),
                ('problem2', models.IntegerField()),
                ('problem3', models.IntegerField()),
                ('problem4', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='locn',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='clg',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dbfolder',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mtest',
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='col',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mrnd.college'),
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='dbname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='emailid',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='mocktest',
        ),
        migrations.AddField(
            model_name='marks',
            name='stud',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mrnd.student'),
        ),
    ]
