# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0007_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='college',
            new_name='College',
        ),
    ]
