# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0008_auto_20160601_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='problem1',
            new_name='from_custom_base26',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='problem2',
            new_name='get_pig_latin',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='problem3',
            new_name='top_chars',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='problem4',
            new_name='transform',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='stud',
        ),
        migrations.RemoveField(
            model_name='student',
            name='col',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dbname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='College',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrnd.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrnd.College'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dbfolder',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrnd.College'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact',
            field=models.EmailField(max_length=29),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
