# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 06:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=700)),
                ('created', models.DateField(default=datetime.datetime(2016, 6, 28, 6, 36, 13, 437000, tzinfo=utc))),
                ('duedate', models.DateField(default=datetime.datetime(2016, 6, 28, 6, 36, 13, 437000, tzinfo=utc))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField(default=datetime.datetime(2016, 6, 28, 6, 36, 13, 437000, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='li',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TODO.TodoList'),
        ),
    ]
