# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 30, 15, 49, 10, 714000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2016, 6, 30, 15, 49, 10, 714000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 30, 15, 49, 10, 713000, tzinfo=utc)),
        ),
    ]
